### ISSUE TITLE
Crash when lauching the ios app on the device

### ISSUE THREAD

**Issue by ghaiat** [remotium/cordova-plugin-webrtc#2]
Hello
The app craches just after installing the plugin with the following stack trace.
Any idea what is going on  ?

https://www.dropbox.com/s/j13qnhgchalmunl/Screenshot%202015-06-05%2018.16.10.png?dl=0

**Comment by oNaiPs** [comment]
@ghaiat  I updated the plugin, it'll now automatically fetch the webrtc lib from CocoaPods libjingle_peerconnection file. Could you check again if the problem got resolved?

Thanks

**Comment by ghaiat** [comment]
Hello, sorry for the late reply, but i just installed the latest version of the plugin and my app is still crashing when i start a video call

https://www.dropbox.com/s/t7qc04gk4sow4ld/Screenshot%202015-07-06%2014.02.15.png?dl=0

**Comment by oNaiPs** [comment]
This project is deprecated in favor of https://github.com/eface2face/cordova-plugin-iosrtc.
Please use that instead. Thanks
